version: "3.7"
services:
  kali:
    build: 
      context: ./
      dockerfile: Dockerfile-custom
      network: host
    image: sec-srv:9005/kali-default:latest
    network_mode: "host"
    privileged: true
    # restart: ""
    env_file:
      - kali.env
    volumes:
      - "${PWD}:/data"
    command: ["/bin/sleep","10000000"]
    # command: ["/usr/bin/python3","/SentryEye/SentryEyeDaemon.py"]